posts: Posts
category: Category
categories: Categories
tag: Tag
tags: Tags
archives: Archives
about: About
recommendedPosts: Recommended Posts
readMore: Read more
toc: TOC
reprint: Reprint please specify
curr: Current
prev: Previous
next: Next
search: Search
searchTip: Please enter a search keyword
postTagTitle: Post Tags
postCategoryTitle: Post Categories
categoryRadarTitle: Post Categories Radar Chart
categoryNumber: Number of Categories
categoryEmptyTip: Your posts has no categories information yet.
postCharts: Post Charts
postPublishChart: Post Publish Chart
categoriesChart: Categories Chart
top10TagsChart: TOP10 Tags Chart
postsNumberName: Number of posts
maximum: Maximum
minimum: Minimum
average: Average
myProjects: My Projects
mySkills: My Skills
otherSkills: Other Skills
gallery: Gallery