posts: Posts
category: Category
categories: Categories
tag: Tag
tags: Tags
archives: Archives
about: About
contact: Contact
friends: Friends
startRead: Start
recommendedPosts: Recommended Posts
publishDate: Publish Date
updateDate: Update Date
readCount: Read Count
wordCount: Word Count
readTimes: Read Times
Minutes: Min
readMore: Read more
toc: TOC
curr: Current
prev: Previous
next: Next
search: Search
searchTip: Please enter a search keyword
postTagTitle: Post Tags
postCategoryTitle: Post Categories
categoryRadarTitle: Post Categories Radar Chart
categoryNumber: Number of Categories
categoryEmptyTip: Your posts has no categories information yet.
postCharts: Post Charts
postPublishChart: Post Publish Chart
categoriesChart: Categories Chart
top10TagsChart: TOP10 Tags Chart
postsNumberName: Number of posts
maximum: Maximum
minimum: Minimum
average: Average
myProjects: My Projects
mySkills: My Skills
otherSkills: Other Skills
gallery: Gallery
notag: No tag
from: From
reprint: Reprint policy
author: Author
link: Link
use: All articles in this blog are used except for special statements
licensed: reprint polocy. If reproduced, please indicate source
cc_by_url: https://creativecommons.org/licenses/by/4.0/deed.zh
cc_by_name: CC BY 4.0
cc_by_nd_url: https://creativecommons.org/licenses/by-nd/4.0/deed.zh
cc_by_nd_name: CC BY-ND 4.0
cc_by_sa_url: https://creativecommons.org/licenses/by-sa/4.0/deed.zh
cc_by_sa_name: CC BY-SA 4.0
cc_by_nc_url: https://creativecommons.org/licenses/by-nc/4.0/deed.zh
cc_by_nc_name: CC BY-NC 4.0
cc_by_nc_nd_url: https://creativecommons.org/licenses/by-nc-nd/4.0/deed.zh
cc_by_nc_nd_name: CC BY-NC-ND 4.0
cc_by_nc_sa_url: https://creativecommons.org/licenses/by-nc-sa/4.0/deed.zh
cc_by_nc_sa_name: CC BY-NC-SA 4.0
cc_0_url: https://creativecommons.org/publicdomain/zero/1.0/
toTheExtentPossibleUnderLaw: To the extent possible under law,
hasWaivedAllCopyrightAndRelatedOrNeighboringRightsTo: has waived all copyright and related or neighboring rights to
workPublishedFrom: ". This work is published from:"
cc_0_country: United States.
cc_0_content: US
noreprint: This article is not allowed to reprint.
paycontact: Please contact the author
payreprint: to pay for reprinting.
pleaseFollowReprintPolicy: Copied successfully, please follow the reprint policy of this article
checkPolicy: more